# Generated by Django 2.2.2 on 2019-06-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('subtype', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('total_area', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'listings',
                # 'managed': False,
            },
        ),
    ]
